- hosts: all
  roles:
    - bindep
    - ensure-tox
    - revoke-sudo
  tasks:
    - name: Checkout requirements branch for tag
      shell:
        cmd: |
          set -x
          # See if the tag appears on a stable branch
          TARGET_BRANCH=`git -C \
              {{ ansible_user_dir }}/{{ zuul.project.src_dir }} branch -a \
              --contains {{ zuul.ref }} | grep ' stable/' | sort | head -n1`
          # And if it does, then try to check out the same branch of the
          # requirements repo, but if that does not exist then we leave it
          # as we found it
          if [ -n "$TARGET_BRANCH" ]; then
              git checkout $TARGET_BRANCH || true
          fi
        executable: /bin/bash
        chdir: "{{ zuul.projects['git.openstack.org/openstack/requirements'].src_dir }}"
