- hosts: all
  roles:
    - role: bindep
      # NOTE(pabelanger): puppet modules use the build profile to manage
      # dependencies for puppet module build.
      bindep_profile: build
    - revoke-sudo
