- hosts: all
  tasks:
    - name: Collect yaml2ical output
      synchronize:
        dest: "{{ zuul.executor.work_root }}/yaml2ical"
        mode: pull
        src: "src/{{ zuul.project.canonical_name }}/output/"
        verify_host: true

- hosts: localhost
  roles:
    - add-fileserver

- hosts: "{{ fileserver.fqdn }}"
  gather_facts: False
  tasks:

    - name: Upload index files
      copy:
        src: "{{ zuul.executor.work_root }}/yaml2ical/{{ item }}"
        dest: "{{ fileserver.path }}/{{ item }}"
      with_items:
        - index.html
        - irc-meetings.ical

    - name: Copy calendars
      synchronize:
        src: "{{ zuul.executor.work_root }}/yaml2ical/calendars/"
        dest: "{{ fileserver.path }}/calendars"
