- name: Copy the upper-constraints.txt file to the project dir
  copy:
    # copy happens entirely on the remote node
    remote_src: yes
    src: "{{ ansible_user_dir }}/src/git.openstack.org/openstack/requirements/upper-constraints.txt"
    dest: "{{ zuul.project.src_dir }}/upper-constraints.txt"
