- hosts: all
  roles:
    - role: write-root-marker
      when: zuul_success | bool
    - role: fetch-sphinx-output
      sphinx_output_suffix: "/"
      zuul_executor_dest: "{{ zuul.executor.work_root }}/artifacts"
      when: zuul_success | bool

- hosts: localhost
  roles:
    - role: set-service-type-data-fact
      when: zuul_success | bool
    - role: create-afs-token
      when: zuul_success | bool
    - role: upload-afs
      afs_target: "{{ afs.path }}/api-ref/{{ service_type_data.service_type }}"
      when: zuul_success | bool
    - role: destroy-afs-token
      when: zuul_success | bool
