- hosts: all
  roles:
    - role: prepare-docs-for-afs
      when: zuul_success | bool
    - role: write-root-marker
      when: zuul_success | bool
    - role: fetch-sphinx-output
      sphinx_output_suffix: "/"
      zuul_executor_dest: "{{ zuul.executor.work_root }}/artifacts"
      when: zuul_success | bool
