- hosts: all
  roles:
    - fetch-tox-output
    - role: fetch-sphinx-output
      sphinx_output_src: "{{ zuul.project.src_dir }}/publish-docs/"
      zuul_executor_dest: "{{ zuul.executor.work_root }}/artifacts"
      when: zuul_success | bool
