- hosts: all
  roles:
    - role: fetch-sphinx-output
      sphinx_output_suffix: "/"
      zuul_executor_dest: "{{ zuul.executor.work_root }}/artifacts"
      when: zuul_success | bool

- hosts: localhost
  roles:
    - role: add-fileserver
      fileserver: "{{ site_logs }}"

- hosts: "{{ site_logs.fqdn }}"
  gather_facts: False
  tasks:

    - name: Upload specs to fileserver
      synchronize:
        src: "{{ zuul.executor.work_root }}/artifacts/"
        dest: "/srv/static/specs/{{ zuul.project.name }}"
      no_log: true
      when: zuul_success | bool
