- hosts: all
  roles:
    - fetch-tox-output
    - role: fetch-sphinx-output
      sphinx_output_src: "src/{{ zuul.project.canonical_name }}/doc/build/html/"
      zuul_executor_dest: "{{ zuul.executor.work_root }}/artifacts"
      when: zuul_success | bool

- hosts: localhost
  roles:
    - role: add-fileserver
      fileserver: "{{ site_logs }}"

- hosts: "{{ site_logs.fqdn }}"
  gather_facts: False
  tasks:
    - name: Publish service-types-authority data to service-types.openstack.org
      synchronize:
        src: "{{ zuul.executor.work_root }}/artifacts/"
        dest: "/srv/static/service-types/"
      no_log: true
      when: zuul_success | bool
