- hosts: all
  strategy: free

  pre_tasks:
    - name: Generate AFS slug - CentOS
      set_fact:
        afs_slug: "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}"
      when: ansible_distribution == "CentOS"

    - name: Generate AFS slug - Ubuntu
      set_fact:
        afs_slug: "{{ ansible_distribution|lower }}-{{ ansible_distribution_version }}-{{ ansible_architecture }}"
      when: ansible_distribution == "Ubuntu"

    - name: Set fact for AFS dir
      set_fact:
        afs_dir: "/afs/.openstack.org/mirror/wheel/{{ afs_slug }}/"

    - name: Set fact for wheel dir
      set_fact:
        wheel_dir: /opt/wheel/workspace

  roles:
    - create-afs-token
    - copy-wheels
    - destroy-afs-token
