includes:
  - python-file: openstack_functions.py

pipelines:
  - name: check
    description: Newly uploaded patchsets enter this pipeline to receive an initial +/-1 Verified vote from the "Jenkins" user.
    success-message: Build succeeded (check pipeline).
    failure-message: Build failed (check pipeline).  For information on how to proceed, see http://docs.openstack.org/infra/manual/developers.html#automated-testing
    manager: IndependentPipelineManager
    source: gerrit
    precedence: normal
    require:
      open: True
      current-patchset: True
    trigger:
      gerrit:
        - event: patchset-created
        - event: change-restored
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*recheck
        - event: comment-added
          require-approval:
            - Verified: [-1, -2]
              username: jenkins
          approval:
            - Workflow: 1
    success:
      gerrit:
        Verified: 1
    failure:
      gerrit:
        Verified: -1

  - name: gate
    description: Changes that have been approved by core developers are enqueued in order in this pipeline, and if they pass tests, will be merged.
    success-message: Build succeeded (gate pipeline).
    failure-message: Build failed (gate pipeline).  For information on how to proceed, see http://docs.openstack.org/infra/manual/developers.html#automated-testing
    manager: DependentPipelineManager
    source: gerrit
    precedence: high
    require:
      open: True
      current-patchset: True
      approval:
        - Verified: [1, 2]
          username: jenkins
        - Workflow: 1
    trigger:
      gerrit:
        - event: comment-added
          approval:
            - Workflow: 1
        - event: comment-added
          approval:
            - Verified: 1
          username: jenkins
    start:
      gerrit:
        Verified: 0
    success:
      gerrit:
        Verified: 2
        submit: true
    failure:
      gerrit:
        Verified: -2
    window-floor: 20
    window-increase-factor: 2

  - name: post
    description: This pipeline runs jobs that operate after each change is merged.
    manager: IndependentPipelineManager
    source: gerrit
    precedence: low
    trigger:
      gerrit:
        - event: ref-updated
          ref: ^(?!refs/).*$

  - name: release-post
    description: This pipeline runs release-process-critical jobs that operate after specific changes are merged.
    manager: IndependentPipelineManager
    source: gerrit
    precedence: high
    trigger:
      gerrit:
        - event: ref-updated
          ref: ^(?!refs/).*$
    failure:
      smtp:
        from: jenkins@openstack.org
        to: release-job-failures@lists.openstack.org
        subject: 'release-post job for {change.project} failed'

  - name: tag
    description: This pipeline runs jobs in response to any tag event.
    manager: IndependentPipelineManager
    source: gerrit
    precedence: high
    trigger:
      gerrit:
        - event: ref-updated
          ref: ^refs/tags/.*$
    failure:
      smtp:
        from: jenkins@openstack.org
        to: release-job-failures@lists.openstack.org
        subject: 'Tag of {change.project} failed'

  - name: pre-release
    description: This pipeline runs jobs on projects in response to pre-release tags.
    manager: IndependentPipelineManager
    source: gerrit
    precedence: high
    trigger:
      gerrit:
        - event: ref-updated
          ref: ^refs/tags/[0-9]+(\.[0-9]+)*(a|b|rc)[0-9]+$
    failure:
      smtp:
        from: jenkins@openstack.org
        to: release-job-failures@lists.openstack.org
        subject: 'Pre-release of {change.project} failed'

  - name: release
    description: When a commit is tagged as a release, this pipeline runs jobs that publish archives and documentation.
    manager: IndependentPipelineManager
    source: gerrit
    precedence: high
    trigger:
      gerrit:
        - event: ref-updated
          ref: ^refs/tags/[0-9]+(\.[0-9]+)*$
    failure:
      smtp:
        from: jenkins@openstack.org
        to: release-job-failures@lists.openstack.org
        subject: 'Release of {change.project} failed'

  - name: silent
    description: This pipeline is used for silently testing new jobs.
    manager: IndependentPipelineManager
    source: gerrit
    precedence: low
    trigger:
      gerrit:
        - event: patchset-created
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*recheck

  - name: experimental
    description: On-demand pipeline for requesting a run against a set of jobs that are not yet gating. Leave review comment of "check experimental" to run jobs in this pipeline.
    success-message: Build succeeded (experimental pipeline).
    failure-message: Build failed (experimental pipeline).
    manager: IndependentPipelineManager
    source: gerrit
    precedence: normal
    trigger:
      gerrit:
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*check experimental\s*$
    success:
      gerrit: {}
    failure:
      gerrit: {}

  - name: periodic
    description: Jobs in this queue are triggered on a timer.
    manager: IndependentPipelineManager
    source: gerrit
    precedence: low
    trigger:
      timer:
        - time: '0 6 * * *'

  - name: periodic-stable
    description: Periodic checks of the stable branches.
    manager: IndependentPipelineManager
    source: gerrit
    precedence: low
    trigger:
      timer:
        - time: '1 6 * * *'
    failure:
      smtp:
        from: jenkins@openstack.org
        to: openstack-stable-maint@lists.openstack.org
        subject: 'Stable check of {change.project} failed'

  - name: merge-check
    description: >
      Each time a change merges, this pipeline verifies that all open changes
      on the same project are still mergeable.
    failure-message: Build failed (merge-check pipeline).
    manager: IndependentPipelineManager
    ignore-dependencies: true
    source: gerrit
    precedence: low
    require:
      approval:
        - Verified: [1, 2]
          username: jenkins
    trigger:
      zuul:
        - event: project-change-merged
    merge-failure:
      gerrit:
        Verified: -1


project-templates:
  - name: merge-check
    merge-check:
      - noop

  - name: noop-jobs
    check:
      - noop
    gate:
      - noop

jobs:
  - name: ^.*$
    parameter-function: set_node_options
  # -nv jobs are never voting.
  - name: ^.*-nv$
    voting: false

  - name: gate-requirements-python34
    branch: master

  - name: gate-bashate-devstack
    voting: false

########################################################################
# The project list is sorted alphabetically.
########################################################################

projects:
  - name: theopenlab/gophercloud
    template:
      - name: merge-check
      - name: noop-jobs

  - name: theopenlab/cicd
    template:
      - name: merge-check
      - name: noop-jobs