dashboard:
  title: Mosquitto Status
  rows:
    - title: Description
      height: 100px
      panels:
        - title: Description
          content: |
            **This dashboard is managed by [Grafyaml](http://docs.openstack.org/infra/system-config/grafyaml.html).**

            If you would like to make changes to this dashboard, please see the grafana directory in [project-config](https://git.openstack.org/cgit/openstack-infra/project-config/tree/grafana/mosquitto.yaml).
          type: text
    - title: Client Information
      height: 150px
      panels:
        - title: Total Clients
          span: 2
          sparkline:
            full: true
            show: true
          targets:
            - target: stats.gauges.mosquitto.total_clients
          type: singlestat
          valueName: current
        - title: Subscription Count
          span: 2
          sparkline:
            full: true
            show: true
          targets:
            - target: stats.gauges.mosquitto.subscription_count
          type: singlestat
          valueName: current
      showTitle: true
    - title: Connection Information
      height: 250px
      panels:
        - title: Message Rates (messages / minute)
          span: 4
          stack: true
          tooltip:
            value_type: individual
          targets:
            - target: alias(stats.gauges.mosquitto.messages_sent, 'Messages Sent')
            - target: alias(stats.gauges.mosquitto.messages_recieved, 'Messages Received')
            - target: alias(stats.gauges.mosquitto.messages_dropped, 'Messages Dropped')
          seriesOverrides:
            - alias: Max
              stack: False
          type: graph
        - title: Heap Size (Bytes)
          span: 4
          targets:
            - target: stats.gauges.mosquitto.heap_size
          type: graph
        - title: Data Transfered (bytes / minute)
          span: 4
          targets:
            - target: stats.gauges.mosquitto.bytes_sent
            - target: stats.gauges.mosquitto.bytes_recieved
          type: graph
