dashboard:
  title: Tap-as-a-Service Failure Rate
  rows:
    - title: Description
      height: 100px
      panels:
        - title: Description
          content: |
            **This dashboard is managed by [Grafyaml](http://docs.openstack.org/infra/system-config/grafyaml.html).**

            If you would like to make changes to this dashboard, please see the grafana directory in [project-config](https://git.openstack.org/cgit/openstack-infra/project-config/tree/grafana/tap-as-a-service.yaml).
          type: text
    - title: Graphs
      height: 320px
      panels:
        - title: Unit Tests Failure Rates (Check queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-tap-as-a-service-python27-ubuntu-xenial.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-tap-as-a-service-python27-ubuntu-xenial.{SUCCESS,FAILURE})),'24hours'), 'gate-tap-as-a-service-python27-ubuntu-xenial')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-tap-as-a-service-python35.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-tap-as-a-service-python35.{SUCCESS,FAILURE})),'24hours'), 'gate-tap-as-a-service-python35')
          type: graph
        - title: Unit Tests Failure Rates (Gate queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-tap-as-a-service-python27-ubuntu-xenial.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-tap-as-a-service-python27-ubuntu-xenial.{SUCCESS,FAILURE})),'24hours'), 'gate-tap-as-a-service-python27-ubuntu-xenial')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-tap-as-a-service-python35.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-tap-as-a-service-python35.{SUCCESS,FAILURE})),'24hours'), 'gate-tap-as-a-service-python35')
          type: graph
        - title: Tempest Failure Rates (Check queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-tap-as-a-service.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-tap-as-a-service.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-tap-as-a-service')
          type: graph
        - title: Tempest Failure Rates (Gate queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-tap-as-a-service.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-tap-as-a-service.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-tap-as-a-service')
          type: graph
