- hosts: ubuntu-xenial
  roles:
    - fetch-javascript-output
    - version-from-git
    - fetch-javascript-tarball

- hosts: localhost
  roles:
    # project_ver is set by set_fact in version-from-git, but that runs on
    # the remote host, which puts the fact into the hostvars of that host.
    # Now that we're running on localhost, we need to reach in to the remote
    # hosts vars to get the value.
    - role: upload-npm
      project_ver: "{{ hostvars['ubuntu-xenial']['project_ver'] }}"
